stages:
 - build
 - test

variables:
  DOCKER_HOST: tcp://docker:2375

build_backend:
  stage: build
  # image: gradle:jre8-openj9
  script:
    - cd backend
    - gradle assemble
  # rules:
  #   - changes:
  #     - backend/*

test_backend:
  stage: test
  # image: gradle:jre8-openj9
  script:
    - cd backend
    - gradle test
  # rules:
  #   - changes:
  #     - backend/*

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  rules:
    - changes:
      - frontend/*

test_frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm run test
  rules:
    - changes:
      - frontend/*