stages:
 - build
 - test

build:
  stage: build
  script:
    - cd backend
    - gradle assemble
  only:
    refs:
      - master

test:
  stage: test
  script:
    - cd backend
    - gradle test
  only:
    refs:
      - master
